"""Isi buku panduan: bab petugas (Sekretaris, Wali Nagari, Admin), Builder Jenis Surat, dan lampiran."""


def _a(a, *nama):
    return (a[n] for n in nama)


def bab_sekretaris(a):
    bab, akhir, sub, h3, p, langkah, daftar, kotak, gambar, tabel = _a(
        a, 'bab', 'akhir_bab', 'sub', 'h3', 'p', 'langkah', 'daftar', 'kotak', 'gambar', 'tabel')
    return ''.join([
        bab(4, 'Panduan Sekretaris dan Petugas Pelayanan', 'Memeriksa dan memverifikasi pengajuan, melayani warga di kantor, memeriksa koreksi data, dan mengelola data penduduk. Admin Nagari juga dapat mengerjakan semua tugas di bab ini.'),
        sub('4.1', 'Tugas dan dasbor petugas'),
        p('Petugas pelayanan bertugas memastikan setiap pengajuan benar sebelum diteruskan ke Wali Nagari. Tugas harian petugas adalah:'),
        daftar('Memeriksa pengajuan di <span class="mn">Antrean Verifikasi</span>, lalu memverifikasi atau menolaknya.',
               'Membuat pengajuan untuk warga yang datang langsung ke kantor (<span class="mn">Pengajuan Petugas</span>).',
               'Memeriksa permintaan perubahan data warga (<span class="mn">Koreksi Data Warga</span>).',
               'Menambah dan memperbarui data penduduk (<span class="mn">Data Penduduk</span>).',
               'Menjaga kop surat dan stempel Nagari tetap benar (<span class="mn">Kop &amp; Profil Nagari</span>).'),
        p('Dasbor menampilkan empat angka: <b>Perlu verifikasi</b>, <b>Koreksi data menunggu</b>, <b>Menunggu tanda tangan</b>, dan <b>Terbit hari ini</b>, beserta daftar pengajuan dan koreksi yang perlu segera ditangani.'),
        gambar('s01-dasbor.png', 'Dasbor Sekretaris'),
        kotak('tips', p('Angka berwarna di samping menu <span class="mn">Antrean Verifikasi</span> menunjukkan jumlah pengajuan yang menunggu. Periksa menu ini setiap hari kerja.')),
        sub('4.2', 'Antrean verifikasi'),
        p('Buka menu <span class="mn">Antrean Verifikasi</span>. Pengajuan yang paling lama menunggu tampil paling atas. Setiap baris menampilkan nama dan NIK pemohon, jenis surat, waktu pengajuan, dan jumlah lampiran.'),
        gambar('s02-antrean-verifikasi.png', 'Antrean Verifikasi Berkas'),
        langkah('Gunakan kotak <b>Cari</b> untuk mencari nama atau NIK pemohon, dan ikon corong untuk menyaring berdasarkan jenis surat.',
                'Tekan ikon periksa di ujung kanan baris untuk membuka halaman verifikasi.'),
        gambar('s02b-tombol-periksa.png', 'Ikon untuk membuka halaman verifikasi'),
        kotak('catatan', p('Pengajuan yang dikembalikan Wali Nagari tampil dengan tanda <b>Dikembalikan Wali Nagari</b> beserta alasannya. Periksa ulang pengajuan itu sesuai alasan dari Wali (Subbab 4.6).')),
        sub('4.3', 'Memeriksa pengajuan'),
        p('Halaman verifikasi tersusun mengikuti urutan pemeriksaan:'),
        tabel(['Bagian', 'Yang diperiksa'], [
            ['1. Data Pemohon', 'Data resmi dari data penduduk Nagari: nama, NIK, KK, tempat dan tanggal lahir, alamat, agama, pekerjaan, dan lainnya.'],
            ['2. Rincian Formulir', 'Jawaban warga atas pertanyaan khusus surat.'],
            ['3. Berkas Persyaratan', 'Berkas yang diunggah warga. Berkas wajib bertanda <b>WAJIB</b>.'],
            ['Nomor pada pratinjau', 'Nomor surat yang diusulkan otomatis untuk surat ini.'],
            ['Pratinjau PDF', 'Contoh surat persis seperti yang akan dicetak, bertanda DRAFT / SIMULASI.'],
        ]),
        gambar('s03-rincian-verifikasi.png', 'Halaman verifikasi lengkap: data pemohon, jawaban, berkas, nomor, dan pratinjau surat', 'tinggi'),
        h3('Memeriksa berkas'),
        p('Tekan gambar berkas atau tombol <b>Perbesar</b> untuk membukanya dalam ukuran besar. Gunakan tombol <b>−</b> dan <b>+</b> untuk memperkecil atau memperbesar, tombol putar untuk memutar gambar, dan tombol <b>Buka Berkas di Tab Baru</b> untuk membuka berkas PDF.'),
        gambar('s04-perbesar-berkas.png', 'Berkas diperbesar untuk diperiksa'),
        h3('Daftar periksa sebelum memverifikasi'),
        daftar('Nama dan NIK pada berkas sama dengan data pemohon.',
               'Berkas wajib lengkap, terbaca jelas, dan masih berlaku.',
               'Jawaban formulir masuk akal dan sesuai berkas.',
               'Kalimat dan data pada pratinjau surat sudah benar.',
               'Nomor surat sesuai buku register Nagari.'),
        sub('4.4', 'Nomor surat'),
        p('Nomor surat diusulkan otomatis dengan melanjutkan nomor tertinggi yang sudah terbit. Biasanya Anda tidak perlu mengubahnya. Ubah hanya bila nomor harus disesuaikan dengan buku register manual.'),
        langkah('Tekan <span class="tbl">Ubah nomor</span> di kanan atas halaman verifikasi.',
                'Ubah <b>Nomor surat lengkap</b>. Angka urut di dalam nomor otomatis disalin ke kolom <b>Angka urut untuk kelanjutan otomatis</b>.',
                'Tekan <span class="tbl">Simpan dan perbarui pratinjau</span>. Pratinjau surat ikut berganti.'),
        gambar('s05-dialog-ubah-nomor.png', 'Jendela Ubah Nomor Surat'),
        kotak('catatan', p('Nomor masih dapat diubah sampai Wali Nagari menerbitkan surat. Setelah terbit, nomor dikunci permanen.')),
        sub('4.5', 'Memverifikasi atau menolak pengajuan'),
        gambar('s03b-tombol-verifikasi.png', 'Tiga tombol utama: 1 Ubah nomor, 2 Tolak, 3 Setujui &amp; Verifikasi'),
        h3('Memverifikasi (menyetujui)'),
        langkah('Setelah semua benar, tekan <span class="tbl">Setujui &amp; Verifikasi</span>.',
                'Periksa sekali lagi nomor surat pada jendela konfirmasi.',
                'Tekan <span class="tbl">Ya, Setujui &amp; Verifikasi</span>. Pengajuan pindah ke Antrean Tanda Tangan Wali Nagari, dan warga menerima notifikasi.'),
        gambar('s06-dialog-verifikasi.png', 'Konfirmasi verifikasi berkas'),
        kotak('penting', p('Verifikasi hanya dapat dilakukan bila <b>stempel Nagari</b> sudah diunggah dan <b>Wali Nagari aktif</b> sudah diatur. Jika belum, halaman menampilkan peringatan beserta tombol pintas <span class="tbl">Unggah stempel</span> atau <span class="tbl">Atur Wali Nagari</span>.')),
        h3('Menolak'),
        langkah('Tekan <span class="tbl">Tolak</span>.',
                'Tulis <b>Alasan Penolakan Berkas</b> dengan jelas dan sopan, misalnya "Foto KK buram, mohon unggah foto yang jelas". Alasan ini dibaca warga.',
                'Centang berkas yang <b>harus diunggah ulang</b>. Berkas yang dicentang tidak dipakai otomatis lagi saat warga mengajukan ulang.',
                'Tekan <span class="tbl">Tolak Pengajuan Ini</span>. Warga menerima notifikasi dan dapat mengajukan ulang.'),
        gambar('s08-dialog-tolak.png', 'Jendela penolakan: alasan dan berkas yang harus diunggah ulang'),
        kotak('tips', p('Tulis alasan yang menyebutkan apa yang harus diperbaiki, bukan hanya "berkas tidak sesuai". Alasan yang jelas membuat warga tidak perlu bertanya ke kantor.')),
        sub('4.6', 'Pengajuan yang dikembalikan Wali Nagari'),
        p('Wali Nagari dapat mengembalikan surat yang belum ditandatangani, misalnya karena ada data atau nomor yang perlu diperbaiki. Pengajuan itu kembali ke Antrean Verifikasi dengan tanda <b>Dikembalikan Wali Nagari</b> dan alasannya. Nomor usulan sebelumnya dilepas.'),
        langkah('Buka pengajuan tersebut dan baca alasan dari Wali Nagari.',
                'Jika yang perlu diperbaiki adalah nomor surat, sesuaikan dengan <span class="tbl">Ubah nomor</span>, lalu verifikasi ulang.',
                'Jika isian atau berkas warga yang salah, <span class="tbl">Tolak</span> pengajuan dengan alasan yang jelas agar warga memperbaikinya.'),
        sub('4.7', 'Pengajuan petugas untuk warga yang datang ke kantor'),
        p('Gunakan menu <span class="mn">Pengajuan Petugas</span> untuk warga yang datang langsung ke kantor Nagari, misalnya warga yang tidak mempunyai HP. Dokumen fisik diperiksa langsung, sehingga unggahan berkas <b>tidak wajib</b>. Pengajuan yang dibuat petugas <b>langsung terverifikasi</b> dan masuk ke Antrean Tanda Tangan Wali Nagari.'),
        langkah('Buka <span class="mn">Pengajuan Petugas</span>, lalu tekan <span class="tbl">Buat Pengajuan untuk Warga</span>.',
                '<b>Langkah 1 — Pilih warga pemohon.</b> Tekan kolom pilihan, ketik NIK atau nama warga, lalu pilih dari daftar. Data resmi warga tampil untuk diperiksa.',
                '<b>Langkah 2 — Pilih surat.</b> Pilih jenis surat yang diminta warga.',
                '<b>Langkah 3 — Isi formulir.</b> Isi pertanyaan surat berdasarkan keterangan dan dokumen warga.',
                '<b>Langkah 4 — Berkas dan tinjauan.</b> Unggah berkas bila perlu (opsional), periksa <b>Nomor surat</b> yang diusulkan, lalu periksa ringkasan.',
                'Tekan <span class="tbl">Kirim pengajuan warga</span>.'),
        gambar('s15-cari-warga.png', 'Mencari warga dengan NIK atau nama'),
        gambar('s17-pengajuan-petugas-langkah4.png', 'Langkah 4: berkas opsional, nomor surat, dan ringkasan', 'tinggi'),
        kotak('catatan', p('Jika stempel atau Wali Nagari belum siap, pengajuan tetap tersimpan dan menunggu di Antrean Verifikasi. Nomor surat dipilih saat verifikasi.')),
        kotak('penting', p('Warga yang datanya belum lengkap, atau berstatus meninggal atau pindah, tidak dapat dipilih sebagai pemohon. Lengkapi atau perbaiki data penduduknya terlebih dahulu (Subbab 4.9).')),
        sub('4.8', 'Memeriksa koreksi data warga'),
        p('Permintaan perubahan data dari warga masuk ke menu <span class="mn">Koreksi Data Warga</span>. Data resmi baru berubah setelah Anda menyetujuinya.'),
        langkah('Buka <span class="mn">Koreksi Data Warga</span>, lalu buka permintaan yang berstatus <b>Menunggu petugas</b>.',
                'Bandingkan <b>Data saat diajukan</b> dengan <b>Usulan warga</b>. Bila perlu, minta warga menunjukkan dokumen aslinya (KTP/KK).',
                'Jika benar, tekan <span class="tbl">Setujui &amp; Perbarui Data</span>, lalu <span class="tbl">Konfirmasi</span>. Data resmi langsung berubah.',
                'Jika tidak sesuai, tekan <span class="tbl">Tolak Permintaan</span> dan tulis alasannya.'),
        gambar('s10-koreksi-data-rincian.png', 'Rincian permintaan koreksi: data lama dan usulan warga'),
        gambar('s11-dialog-setujui-koreksi.png', 'Konfirmasi persetujuan koreksi data'),
        kotak('catatan', p('Bila NIK atau tanggal lahir warga diubah, akun login warga ikut menyesuaikan: warga masuk dengan NIK baru. Jika warga masih memakai sandi awal, sandi awalnya mengikuti tanggal lahir baru.')),
        sub('4.9', 'Mengelola data penduduk'),
        p('Menu <span class="mn">Data Penduduk</span> berisi seluruh penduduk Nagari. Data ini adalah sumber data diri pada setiap surat.'),
        gambar('s23-data-penduduk.png', 'Daftar penduduk'),
        h3('Menambah penduduk'),
        langkah('Tekan <span class="tbl">Tambah Penduduk</span>.',
                'Isi data wajib: NIK (16 angka), nama lengkap, jenis kelamin, tempat lahir, dan tanggal lahir.',
                'Lengkapi jorong, agama, status perkawinan, pekerjaan, pendidikan, kewarganegaraan, dan nomor HP. Data ini dibutuhkan agar warga dapat mengajukan surat.',
                'Pilih <b>Status Penduduk</b>: Aktif, Meninggal, atau Pindah.',
                'Tekan <span class="tbl">Simpan</span>. Akun login warga dibuat otomatis dengan sandi awal tanggal lahir.'),
        gambar('s24-tambah-penduduk.png', 'Formulir tambah penduduk'),
        h3('Mengubah data, status, dan sandi'),
        tabel(['Kebutuhan', 'Caranya'], [
            ['Memperbaiki data', 'Tekan ikon ubah (<i>Ubah Data Penduduk</i>) pada baris penduduk, perbaiki, lalu simpan.'],
            ['Penduduk meninggal atau pindah', 'Ubah <b>Status Penduduk</b> menjadi Meninggal atau Pindah. Data tetap tersimpan, tetapi surat tidak dapat lagi diajukan atas namanya.'],
            ['Warga lupa kata sandi', 'Tekan ikon <b>Reset kata sandi warga</b>, lalu <span class="tbl">Konfirmasi</span>. Sandi kembali menjadi tanggal lahir (DDMMYYYY). Pastikan identitas warga sudah diperiksa sebelum mereset.'],
            ['Mencari penduduk', 'Ketik nama atau NIK pada kotak Cari, atau saring menurut jorong, status, jenis kelamin, agama, status perkawinan, pekerjaan, dan pendidikan.'],
            ['Menghapus penduduk', 'Hanya Admin. Penduduk yang sudah mempunyai riwayat surat, dokumen, atau permintaan perubahan tidak dapat dihapus; ubah statusnya saja.'],
        ]),
        gambar('s28-dialog-reset-sandi.png', 'Konfirmasi reset kata sandi warga'),
        h3('Impor dan ekspor data penduduk'),
        p('Tombol <span class="tbl">Impor / Ekspor</span> berisi tiga pilihan:'),
        tabel(['Pilihan', 'Kegunaan'], [
            ['Unduh Template', 'Mengunduh berkas Excel kosong berisi kolom yang benar, daftar pilihan (dropdown), dan petunjuk pengisian.'],
            ['Impor dari Excel', 'Menambah banyak penduduk sekaligus dari berkas .xlsx atau .csv (maksimal 15 MB). Setiap baris juga membuat akun login warga.'],
            ['Ekspor Data Excel', 'Mengunduh seluruh data penduduk dalam format yang sama dengan template, sehingga dapat diimpor kembali ke sistem baru.'],
        ]),
        gambar('a02-menu-impor-ekspor.png', 'Menu Impor / Ekspor'),
        langkah('Tekan <span class="tbl">Impor / Ekspor</span> → <span class="mn">Unduh Template</span>, lalu isi sheet <b>Data Warga</b>. Jangan mengubah baris judul (baris 1).',
                'Isi kolom wajib bertanda bintang: <b>nama, nik, sex, tempatlahir, tanggallahir</b>. Tanggal lahir ditulis <i>tahun-bulan-tanggal</i>, misalnya 1990-05-17.',
                'Kolom pilihan (jenis kelamin, jorong, agama, status kawin, pekerjaan, pendidikan, kewarganegaraan, status penduduk) dipilih dari dropdown agar tidak salah ketik.',
                'Simpan berkas sebagai .xlsx. Berkas .xls lama harus disimpan ulang sebagai .xlsx.',
                'Tekan <span class="tbl">Impor / Ekspor</span> → <span class="mn">Impor dari Excel</span>, pilih berkas, lalu tekan <span class="tbl">Mulai Impor</span>. Jangan menutup halaman selama proses berjalan.',
                'Baca <b>Hasil Impor Warga</b>. Baris yang bermasalah tercantum beserta nomor baris dan alasannya. Perbaiki baris itu di berkas, lalu impor ulang bagian itu saja.'),
        gambar('a03-dialog-impor.png', 'Jendela impor warga'),
        gambar('a05-laporan-impor.png', 'Hasil impor: 2 berhasil, 1 baris ditolak beserta alasannya'),
        kotak('penting', p('Impor hanya <b>menambah warga baru</b>. Baris dengan NIK yang sudah terdaftar akan ditolak. Untuk memperbaiki data warga yang sudah ada, gunakan tombol ubah di Data Penduduk.')),
        sub('4.10', 'Arsip, riwayat, dan rekap laporan'),
        h3('Arsip &amp; Riwayat Surat'),
        p('Menu <span class="mn">Arsip &amp; Riwayat Surat</span> menampilkan semua pengajuan dengan semua status. Gunakan ikon corong untuk menyaring menurut status, jenis surat, jorong pemohon, dan rentang tanggal.'),
        gambar('s21-arsip-filter.png', 'Arsip dan pilihan penyaring'),
        daftar('Ikon mata (<b>Lihat arsip</b>) membuka rincian lengkap pengajuan.',
               'Ikon unduh (<b>Unduh surat</b>) mengunduh PDF resmi surat yang sudah terbit.',
               '<b>Lihat draf</b> membuka pratinjau surat yang belum terbit.'),
        h3('Rekap Laporan Surat'),
        p('Menu <span class="mn">Rekap Laporan Surat</span> menampilkan jumlah surat per jenis layanan: total masuk, menunggu verifikasi, menunggu tanda tangan, diterbitkan, dan ditolak. Pilih <b>Tahun</b> dan <b>Bulan</b>, lalu tekan <span class="tbl">Unduh Rekap Spreadsheet (.xlsx)</span> untuk laporan berkala.'),
        gambar('s22-rekap.png', 'Rekap dan statistik pelayanan surat'),
        sub('4.11', 'Kop surat, stempel, dan data jorong'),
        h3('Kop &amp; Profil Nagari'),
        p('Menu <span class="mn">Kop &amp; Profil Nagari</span> mengatur kop surat yang tercetak di setiap surat: nama kabupaten, kecamatan, nagari, provinsi, alamat kantor, telepon, email, website, logo, dan <b>stempel resmi</b>.'),
        gambar('s25-kop-profil.png', 'Pengaturan kop surat dan stempel', 'tinggi'),
        langkah('Ubah teks kop atau kontak bila ada perubahan. Pratinjau kop di bagian atas menunjukkan hasilnya setelah disimpan.',
                'Untuk mengganti stempel, hapus gambar lama lalu unggah gambar stempel baru berformat <b>PNG berlatar transparan</b>.',
                'Tekan <span class="tbl">Simpan Perubahan</span>.'),
        kotak('penting', p('Surat tidak dapat diverifikasi maupun diterbitkan sebelum stempel diunggah. Stempel hanya tercetak pada surat yang sudah terbit, tidak pada draf atau simulasi.')),
        h3('Data Jorong'),
        p('Menu <span class="mn">Data Jorong</span> menampilkan daftar jorong di Nagari Taram dan jumlah penduduknya. Sekretaris dan Wali Nagari dapat melihatnya; menambah, mengubah, dan menghapus jorong dilakukan Admin (Subbab 6.4).'),
        akhir(),
    ])


def bab_wali(a):
    bab, akhir, sub, h3, p, langkah, daftar, kotak, gambar, tabel = _a(
        a, 'bab', 'akhir_bab', 'sub', 'h3', 'p', 'langkah', 'daftar', 'kotak', 'gambar', 'tabel')
    return ''.join([
        bab(5, 'Panduan Wali Nagari', 'Meninjau, menandatangani, dan menerbitkan surat resmi Nagari secara online.'),
        sub('5.1', 'Tugas dan dasbor Wali Nagari'),
        p('Wali Nagari adalah satu-satunya pengguna yang dapat menandatangani dan menerbitkan surat. Surat yang masuk ke Wali sudah diperiksa dan diverifikasi petugas.'),
        daftar('Meninjau surat di <span class="mn">Antrean Tanda Tangan</span>.',
               'Menandatangani dan menerbitkan surat.',
               'Mengembalikan surat ke petugas bila ada yang perlu diperbaiki.',
               'Memantau arsip dan rekap pelayanan surat.'),
        gambar('k01-dasbor-wali.png', 'Dasbor Wali Nagari'),
        kotak('penting', p('Sebelum dapat menerbitkan surat, <b>gambar tanda tangan Wali Nagari</b> harus sudah diunggah (Subbab 5.5), dan stempel Nagari harus sudah tersedia. Akun Wali juga harus tertaut ke data pejabat Wali Nagari yang aktif.')),
        sub('5.2', 'Antrean tanda tangan'),
        p('Buka menu <span class="mn">Antrean Tanda Tangan</span>. Daftar ini berisi surat yang sudah diverifikasi petugas, lengkap dengan nama pemohon, jenis surat, nomor usulan, dan waktu siap ditandatangani.'),
        gambar('k02b-tombol-tinjau.png', 'Antrean tanda tangan. Tekan tombol bertanda 1 untuk meninjau'),
        p('Tekan <span class="tbl">Tinjau, tanda tangani &amp; terbitkan</span> pada baris surat untuk membuka halaman peninjauan.'),
        sub('5.3', 'Meninjau dan menerbitkan surat'),
        p('Halaman peninjauan menampilkan <b>nomor surat</b> dan <b>pratinjau PDF</b> surat persis seperti yang akan terbit.'),
        gambar('k03b-tombol-wali.png', 'Tombol Wali Nagari: 1 Ubah nomor, 2 Kembalikan ke petugas, 3 Tanda tangani &amp; terbitkan'),
        langkah('Baca pratinjau surat: nama pemohon, data, kalimat keterangan, dan nomor surat.',
                'Bila nomor perlu disesuaikan, tekan <span class="tbl">Ubah nomor</span>, ubah nomor lengkap, lalu simpan. Pratinjau ikut berganti.',
                'Bila semua benar, tekan <span class="tbl">Tanda tangani &amp; terbitkan</span>.',
                'Pada jendela konfirmasi, tekan <span class="tbl">Ya, tanda tangani &amp; terbitkan</span>.',
                'Surat terbit: nomor dikunci, PDF resmi dibuat dengan tanda tangan dan stempel, dan warga menerima notifikasi.'),
        gambar('k05-dialog-terbitkan.png', 'Konfirmasi penerbitan surat'),
        kotak('penting', p('Setelah diterbitkan, nomor surat <b>tidak dapat diubah</b> dan surat tidak dapat dibatalkan. Pastikan semua sudah benar sebelum menekan tombol konfirmasi.')),
        p('Pada surat yang terbit, tanda tangan dicetak lebih dahulu, lalu stempel dibubuhkan di atas sepertiga kiri tanda tangan, seperti surat yang ditandatangani dan dicap langsung.'),
        sub('5.4', 'Mengembalikan surat ke petugas'),
        p('Gunakan bila surat belum layak ditandatangani, misalnya ada data yang keliru atau nomor yang perlu diperiksa ulang.'),
        langkah('Tekan <span class="tbl">Kembalikan ke petugas</span>.',
                'Tulis <b>Alasan dikembalikan</b> dengan jelas, misalnya "Nama usaha berbeda dengan foto papan nama".',
                'Tekan <span class="tbl">Kembalikan</span>. Surat kembali ke Antrean Verifikasi, dan nomor usulannya dilepas.'),
        gambar('k04-dialog-kembalikan.png', 'Jendela pengembalian surat ke petugas'),
        kotak('catatan', p('Petugas kemudian memperbaiki nomor lalu memverifikasi ulang, atau menolak pengajuan agar warga memperbaiki isian atau berkasnya.')),
        sub('5.5', 'Mengunggah tanda tangan Wali Nagari'),
        p('Tanda tangan dapat diunggah sendiri oleh Wali Nagari melalui halaman profil, atau oleh Admin melalui menu Pejabat Nagari.'),
        langkah('Buka menu akun di kanan atas, lalu pilih <span class="mn">Profil Saya</span>.',
                'Pada bagian <b>Tanda Tangan Wali Nagari</b>, hapus gambar lama bila ada, lalu unggah gambar tanda tangan baru: PNG berlatar transparan (disarankan) atau JPG, maksimal 5 MB.',
                'Tekan <span class="tbl">Simpan Perubahan</span>.'),
        gambar('k08-profil-wali.png', 'Halaman profil Wali Nagari dengan bagian tanda tangan'),
        kotak('tips', p('Gunakan tanda tangan yang dipindai dari kertas putih, lalu hapus latarnya sehingga transparan. Tanda tangan dicetak selebar ±5 cm, jadi gambar yang terlalu kecil akan tampak buram.')),
        sub('5.6', 'Arsip, rekap, dan data penduduk'),
        daftar('<span class="mn">Arsip &amp; Riwayat Surat</span>: melihat dan mengunduh semua surat yang sudah terbit (cara pemakaiannya sama dengan Subbab 4.10).',
               '<span class="mn">Rekap Laporan Surat</span>: melihat statistik pelayanan per jenis surat, per bulan atau per tahun, dan mengunduhnya sebagai Excel.',
               '<span class="mn">Data Penduduk</span> dan <span class="mn">Data Jorong</span>: hanya untuk dilihat; perubahan data dilakukan petugas.'),
        gambar('k07-arsip-wali.png', 'Arsip surat dari akun Wali Nagari'),
        akhir(),
    ])


def bab_admin(a):
    bab, akhir, sub, h3, p, langkah, daftar, kotak, gambar, tabel = _a(
        a, 'bab', 'akhir_bab', 'sub', 'h3', 'p', 'langkah', 'daftar', 'kotak', 'gambar', 'tabel')
    return ''.join([
        bab(6, 'Panduan Admin Nagari', 'Admin Nagari mengerjakan semua tugas Sekretaris (Bab 4), ditambah pengaturan pejabat, jorong, log aktivitas, dan jenis surat (Bab 7).'),
        sub('6.1', 'Tugas Admin Nagari'),
        tabel(['Tugas', 'Menu', 'Dibahas di'], [
            ['Memverifikasi pengajuan, pengajuan petugas, koreksi data, data penduduk (termasuk impor/ekspor), arsip, rekap, kop dan stempel', 'Sama dengan Sekretaris', 'Bab 4'],
            ['Membuat dan mengubah jenis surat', 'Builder Jenis Surat', 'Bab 7'],
            ['Mengatur Wali Nagari dan Sekretaris beserta akun dan tanda tangannya', 'Pejabat Nagari', 'Subbab 6.2'],
            ['Menambah, mengubah, dan menghapus jorong', 'Data Jorong', 'Subbab 6.4'],
            ['Memeriksa jejak kegiatan pengguna', 'Log Aktivitas', 'Subbab 6.3'],
            ['Menghapus data penduduk yang belum mempunyai riwayat', 'Data Penduduk', 'Subbab 4.9'],
        ]),
        gambar('a01-dasbor-admin.png', 'Dasbor Admin Nagari dengan menu tambahan Builder Jenis Surat, Pejabat Nagari, dan Log Aktivitas'),
        sub('6.2', 'Pejabat Nagari dan akun petugas'),
        p('Menu <span class="mn">Pejabat Nagari</span> berisi Wali Nagari dan Sekretaris Nagari beserta akun login dan tanda tangannya. Akun pejabat dibuat sekaligus saat data pejabat ditambahkan.'),
        gambar('a06-pejabat-nagari.png', 'Daftar pejabat Nagari'),
        h3('Menambah pejabat'),
        langkah('Tekan <span class="tbl">Tambah Pejabat</span>.',
                'Pilih <b>Jabatan</b> (Wali Nagari atau Sekretaris Nagari), isi nama lengkap beserta gelar, NIP (kosongkan bila bukan ASN), dan tahun mulai menjabat.',
                'Biarkan <b>Status Menjabat Aktif</b> menyala. Hanya boleh ada satu pejabat aktif per jabatan; pejabat aktif sebelumnya otomatis dinonaktifkan.',
                'Untuk Wali Nagari, unggah <b>gambar tanda tangan</b>.',
                'Isi <b>Akun Login Pejabat</b>: username, email (opsional), dan kata sandi minimal 8 karakter. Berikan kepada pejabat yang bersangkutan dan minta ia menggantinya setelah masuk.',
                'Tekan <span class="tbl">Simpan Data</span>.'),
        gambar('a07-tambah-pejabat.png', 'Formulir tambah pejabat dan akun loginnya', 'tinggi'),
        kotak('penting', p('Saat Wali Nagari berganti, tambahkan Wali Nagari baru sebagai pejabat aktif beserta tanda tangannya. Surat yang sudah terbit tetap memakai nama dan tanda tangan Wali yang menerbitkannya.')),
        h3('Mengubah atau menonaktifkan pejabat'),
        p('Tekan ikon ubah pada baris pejabat untuk mengganti data, kata sandi akun, atau tanda tangan. Matikan <b>Status Menjabat Aktif</b> dan isi tahun selesai bila masa jabatannya berakhir.'),
        sub('6.3', 'Log aktivitas'),
        p('Menu <span class="mn">Log Aktivitas</span> mencatat semua kegiatan penting: verifikasi, penolakan, penerbitan, perubahan data penduduk, perubahan jenis surat, impor/ekspor, perubahan pejabat dan stempel, serta login. Catatan tidak dapat diubah atau dihapus.'),
        gambar('a08-log-aktivitas.png', 'Daftar log aktivitas'),
        langkah('Saring menurut <b>Jenis Aksi</b> dan rentang tanggal untuk mencari kejadian tertentu.',
                'Tekan <b>Rincian</b> untuk melihat siapa yang melakukan, kapan, dan data sebelum serta sesudah perubahan.'),
        gambar('a09-rincian-log.png', 'Rincian satu aktivitas'),
        sub('6.4', 'Data jorong'),
        p('Jorong dipakai pada alamat penduduk dan alamat di surat. Admin dapat menambah, mengubah, dan menghapus jorong.'),
        langkah('Buka <span class="mn">Data Jorong</span>, lalu tekan <span class="tbl">Tambah Jorong</span>.',
                'Isi nama jorong, lalu simpan.',
                'Untuk mengubah, tekan ikon ubah pada baris jorong. Jorong yang masih mempunyai penduduk tidak dapat dihapus.'),
        gambar('a10-tambah-jorong.png', 'Menambah data jorong'),
        akhir(),
    ])


def bab_builder(a):
    bab, akhir, sub, h3, p, langkah, daftar, kotak, gambar, tabel = _a(
        a, 'bab', 'akhir_bab', 'sub', 'h3', 'p', 'langkah', 'daftar', 'kotak', 'gambar', 'tabel')
    return ''.join([
        bab(7, 'Builder Jenis Surat', 'Panduan lengkap Admin Nagari untuk membuat dan mengubah jenis surat: pertanyaan untuk warga, isi surat, berkas persyaratan, dan pembukaan layanan.'),
        sub('7.1', 'Cara kerja Builder Jenis Surat'),
        p('Builder Jenis Surat dipakai untuk membuat surat keterangan baru tanpa bantuan programmer. Satu jenis surat terdiri dari lima bagian, dan setiap bagian dikerjakan pada satu langkah:'),
        tabel(['Langkah', 'Isinya', 'Hasilnya'], [
            ['1. Nama &amp; nomor', 'Nama surat, kode klasifikasi, kode unit, dan aturan penomoran', 'Judul dan nomor surat'],
            ['2. Form warga', 'Pertanyaan tambahan yang harus dijawab warga', 'Formulir pada langkah 3 pengajuan warga'],
            ['3. Isi surat', 'Kalimat surat dan letak data warga', 'Isi PDF surat'],
            ['4. Berkas', 'Dokumen yang harus diunggah', 'Daftar berkas pada langkah 4 pengajuan warga'],
            ['5. Aktifkan', 'Status layanan dan pemeriksaan akhir', 'Surat dapat atau belum dapat diajukan warga'],
        ]),
        h3('Tiga hal yang perlu diketahui sejak awal'),
        daftar('<b>Data diri pemohon sudah otomatis.</b> Nama, NIK, tempat dan tanggal lahir, jenis kelamin, agama, pekerjaan, alamat, dan data diri lain diambil dari data penduduk. Jangan membuat pertanyaan untuk data ini.',
               '<b>Jawaban warga masuk ke surat dengan sendirinya.</b> Setiap pertanyaan yang Anda buat di langkah 2 langsung ditambahkan ke isi surat di langkah 3. Bila pertanyaan diubah atau dihapus, isi surat ikut menyesuaikan.',
               '<b>Anda tidak perlu mengenal kode atau variabel.</b> Semua diatur dengan memilih dari daftar dan menulis kalimat biasa.'),
        kotak('tips', p('Tombol <span class="tbl">Panduan 5 langkah</span> tersedia di setiap langkah. Tombol ini membuka ringkasan cara mengisi langkah tersebut.')),
        gambar('b05-panduan-5-langkah.png', 'Jendela Panduan 5 langkah di dalam aplikasi'),
        sub('7.2', 'Daftar jenis surat'),
        p('Buka menu <span class="mn">Builder Jenis Surat</span>. Daftar menampilkan setiap jenis surat beserta kode klasifikasi, unit, status, jumlah pertanyaan (<i>Jumlah Field</i>), dan jumlah syarat dokumen.'),
        gambar('b01-daftar-jenis-surat.png', 'Daftar jenis surat'),
        tabel(['Status', 'Artinya'], [
            ['<b>Aktif (Portal)</b>', 'Warga dapat mengajukan surat ini.'],
            ['<b>Draft (Uji Coba)</b>', 'Rancangan. Hanya terlihat petugas; warga belum dapat mengajukan.'],
            ['<b>Nonaktif</b>', 'Pengajuan baru ditutup. Pengajuan lama tetap dapat diproses.'],
        ]),
        p('Di ujung kanan setiap baris ada ikon <b>Simulasi PDF</b> (melihat contoh surat) dan <b>Ubah Jenis Surat</b>. Untuk membuat jenis surat baru, tekan <span class="tbl">Tambah Jenis Surat</span>.'),
        sub('7.3', 'Langkah 1 — Nama dan nomor surat'),
        gambar('b03-langkah1-nama-nomor.png', 'Langkah 1: 1 nama surat, 2 kode klasifikasi, 3 kode unit'),
        langkah('Isi <b>Nama yang akan dilihat warga</b> dengan nama resmi surat, misalnya <i>Surat Keterangan Belum Menikah</i>. Nama ini juga menjadi judul surat.',
                'Periksa <b>Kode klasifikasi</b> sesuai buku register Nagari. Nilai awalnya 400.10.2.2.',
                'Periksa <b>Kode unit</b>, yaitu unit yang menerbitkan surat. Nilai awalnya TUU.',
                'Lihat kotak <b>Pratinjau hasil format nomor surat resmi</b>. Kotak ini menunjukkan bentuk nomor untuk surat pertama, misalnya <i>400.10.2.2/001/TUU/2026</i>.'),
        h3('Pengaturan nomor lanjutan'),
        p('Bagian ini tertutup karena nilai awalnya sudah sesuai untuk sebagian besar surat. Buka hanya bila buku register Nagari memakai aturan lain.'),
        gambar('b04-nomor-lanjutan.png', 'Pengaturan nomor lanjutan yang dibuka', 'tinggi'),
        tabel(['Pengaturan', 'Pilihan', 'Penjelasan'], [
            ['Nomor urut dihitung untuk', 'Jenis surat ini saja · Semua jenis dengan kode klasifikasi yang sama · Seluruh jenis surat', 'Menentukan siapa yang berbagi urutan angka. Umumnya setiap jenis surat mempunyai urutannya sendiri.'],
            ['Susunan nomor surat', 'Kode klasifikasi / nomor urut / kode unit / tahun · Saya atur susunan sendiri', 'Pilih susunan sendiri hanya bila format register berbeda. Susunan sendiri disusun dari Kode Klasifikasi, Nomor Urut, Kode Unit, dan Tahun.'],
            ['Tampilan angka urut', '001, 002, 003 · 1, 2, 3', 'Dengan atau tanpa angka nol di depan.'],
            ['Mulai ulang nomor', 'Kembali ke 1 setiap awal tahun · Terus bertambah', 'Bila memilih mulai ulang setiap tahun, susunan nomor harus memuat Tahun.'],
        ]),
        kotak('penting', p('Susunan nomor <b>wajib memuat Nomor Urut</b>. Jangan mengubah aturan penomoran jenis surat yang sudah dipakai tanpa persetujuan pimpinan, karena nomor berikutnya akan mengikuti aturan baru.')),
        sub('7.4', 'Langkah 2 — Pertanyaan untuk warga'),
        p('Tambahkan hanya pertanyaan yang khusus untuk surat ini, misalnya nama usaha pada Surat Keterangan Usaha. Data diri pemohon tidak perlu ditanyakan. Bila surat tidak memerlukan pertanyaan tambahan, biarkan daftar kosong.'),
        h3('Menambah pertanyaan'),
        langkah('Tekan <span class="tbl">Tambah pertanyaan</span>.',
                'Isi <b>Pertanyaan yang dilihat warga</b>. Tulis singkat dan jelas, misalnya <i>Keperluan surat</i>. Teks ini juga menjadi judul baris di surat.',
                'Pilih <b>Cara menjawab</b> (lihat tabel di bawah).',
                'Atur sakelar <b>Wajib dijawab</b>. Nyala berarti warga harus menjawab; mati berarti boleh dilewati.',
                'Ulangi untuk pertanyaan berikutnya.'),
        gambar('b07-pertanyaan-pilihan.png', 'Pertanyaan dengan pilihan yang ditulis sendiri: 1 teks pertanyaan, 2 cara menjawab, 3 daftar pilihan', 'potongan'),
        h3('Pilihan "Cara menjawab"'),
        tabel(['Cara menjawab', 'Gunakan untuk', 'Aturan otomatis'], [
            ['Teks singkat', 'Nama, nama usaha, alamat singkat, keperluan', 'Maksimal 255 karakter'],
            ['NIK (16 angka)', 'NIK orang lain: saksi, ayah, ibu, almarhum', 'Harus tepat 16 angka'],
            ['Nomor HP', 'Nomor telepon', 'Hanya angka dan tanda +, 8–20 karakter'],
            ['Email', 'Alamat email', 'Harus berbentuk alamat email'],
            ['Teks panjang', 'Keterangan atau uraian beberapa kalimat', '—'],
            ['Teks panjang berformat', 'Uraian yang memerlukan huruf tebal, miring, atau daftar', '—'],
            ['Angka atau nominal', 'Jumlah, penghasilan, luas', 'Hanya angka; dapat dicetak sebagai Rupiah'],
            ['Tanggal', 'Tanggal kegiatan atau tanggal yang akan datang', 'Dipilih dari kalender'],
            ['Tanggal yang sudah lewat', 'Tanggal lahir, tanggal meninggal, tanggal mulai usaha', 'Tidak boleh melebihi hari ini'],
            ['Pilih satu dari daftar yang saya tulis', 'Pilihan khusus, misalnya keperluan surat', 'Warga hanya dapat memilih dari daftar'],
            ['Pilih dari data Nagari', 'Agama, pekerjaan, pendidikan, status perkawinan, hubungan keluarga, kewarganegaraan, suku, atau jorong', 'Pilihan selalu mengikuti data referensi Nagari'],
            ['Daftar beberapa baris (tabel)', 'Data yang jumlahnya bisa lebih dari satu: anggota keluarga, ahli waris, saudara', 'Setiap baris diisi menurut kolom yang Anda tentukan'],
            ['Unggah berkas tambahan', 'Lampiran khusus yang bukan syarat dokumen umum', 'Tidak dicetak di surat; untuk syarat seperti KTP/KK gunakan langkah 4'],
        ]),
        h3('Pilihan jawaban'),
        p('Untuk <b>Pilih satu dari daftar yang saya tulis</b>, ketik satu pilihan pada kotak <b>Pilihan jawaban</b>, lalu tekan Enter. Ulangi untuk setiap pilihan. Tekan tanda × pada sebuah pilihan untuk menghapusnya.'),
        p('Untuk <b>Pilih dari data Nagari</b>, pilih datanya pada kotak <b>Data yang dipakai sebagai pilihan</b>, misalnya <i>Pekerjaan</i>.'),
        gambar('b08-pertanyaan-data-nagari-bersyarat.png', 'Pertanyaan dari data Nagari yang hanya muncul untuk jawaban tertentu', 'potongan'),
        sub('7.5', 'Langkah 2 — Pengaturan lain, kelompok, dan tabel'),
        p('Setiap pertanyaan mempunyai bagian <b>Pengaturan lain</b> yang tertutup. Tekan judulnya untuk membuka. Bagian ini terbuka sendiri bila salah satu pengaturannya sedang dipakai.'),
        h3('Kapan pertanyaan muncul'),
        p('Pilih <b>Hanya jika warga memilih jawaban tertentu</b>, lalu tentukan <b>Bergantung pada pertanyaan</b> dan <b>Jika jawabannya</b>. Contoh pada gambar sebelumnya: pertanyaan <i>Pekerjaan calon pasangan</i> hanya muncul bila <i>Keperluan surat</i> dijawab <i>Persyaratan menikah</i>. Pertanyaan yang menjadi syarat harus berupa pilihan yang ditulis sendiri dan letaknya di atas.'),
        h3('Kelompok pertanyaan'),
        tabel(['Pilihan "Kelompokkan dengan pertanyaan lain?"', 'Hasilnya pada formulir warga'], [
            ['Tidak', 'Pertanyaan tampil sendiri (paling umum).'],
            ['Ya, tampil bersama dalam satu kelompok', 'Beberapa pertanyaan berjudul sama tampil dalam satu kotak, misalnya <i>Data Ayah</i>.'],
            ['Ya, dan warga boleh memilih tidak mengisi kelompok ini', 'Kelompok tampil dengan sakelar <b>Sertakan …</b>. Pertanyaannya baru muncul dan wajib diisi setelah warga menyalakan sakelar. Cocok untuk data saksi atau data orang tua yang tidak selalu ada.'],
        ]),
        p('Isi <b>Nama kelompok</b> yang sama, misalnya <i>Data Saksi</i>, pada setiap pertanyaan anggota kelompok.'),
        gambar('b09-kelompok-pilihan-warga.png', 'Pertanyaan dalam kelompok "Data Saksi" yang boleh dilewati warga', 'potongan'),
        h3('Jangan cetak jawaban ini di surat'),
        p('Nyalakan bila sebuah jawaban hanya perlu dilihat petugas saat memeriksa, misalnya nomor HP yang bisa dihubungi. Jawaban lain otomatis masuk ke isi surat.'),
        h3('Pertanyaan berbentuk tabel'),
        langkah('Pilih cara menjawab <b>Daftar beberapa baris (tabel)</b>.',
                'Pada bagian <b>Kolom yang diisi pada setiap baris</b>, tekan <span class="tbl">Tambah kolom</span>.',
                'Isi <b>Judul kolom</b> dan pilih <b>Cara mengisi kolom</b> (teks singkat, NIK, angka, tanggal, tanggal yang sudah lewat, atau pilihan).',
                'Atur <b>Wajib diisi</b> untuk setiap kolom, lalu ulangi untuk kolom berikutnya.'),
        gambar('b11-pertanyaan-tabel.png', 'Pertanyaan tabel dengan kolom Nama dan Tanggal lahir', 'potongan'),
        h3('Mengurutkan dan menghapus pertanyaan'),
        p('Seret ikon panah atas-bawah di kiri judul kartu untuk mengubah urutan pertanyaan. Tekan ikon tempat sampah merah untuk menghapus pertanyaan. Judul kartu yang tertutup meringkas pertanyaan, cara menjawab, dan status wajibnya.'),
        kotak('tips', p('Teks pertanyaan boleh diubah kapan saja. Judul baris di surat ikut berganti, kecuali judul itu sudah Anda ubah sendiri di langkah 3.')),
        sub('7.6', 'Langkah 3 — Isi surat'),
        p('Langkah ini menampilkan surat seperti di atas kertas: kop (otomatis), judul dan nomor (otomatis), isi surat yang dapat diubah, dan bingkai tanda tangan (otomatis). Isi surat sudah tersusun dari:'),
        daftar('Kalimat pembuka.',
               'Kotak <b>Rincian data</b> berisi identitas pemohon.',
               'Kotak rincian berisi jawaban dari langkah 2. Jawaban bersyarat atau dalam kelompok yang boleh dilewati masuk ke kotak bertuliskan <i>tampil bila…</i>.',
               'Kotak <b>Tabel isian</b> untuk setiap pertanyaan tabel.',
               'Tulisan <b>[ISI REDAKSI BERDASARKAN HASIL VERIFIKASI]</b> yang harus diganti dengan kalimat keterangan surat.',
               'Kalimat penutup.'),
        gambar('b13-langkah3-isi-surat.png', 'Isi surat yang tersusun otomatis dari pertanyaan di langkah 2', 'tinggi'),
        h3('Mengganti kalimat keterangan'),
        langkah('Klik tulisan <b>[ISI REDAKSI BERDASARKAN HASIL VERIFIKASI]</b>, lalu blok seluruh tulisan itu (klik tiga kali).',
                'Ketik kalimat keterangan surat, misalnya <i>"Nama tersebut di atas sepanjang pengetahuan kami belum pernah menikah dan masih berstatus belum kawin."</i>',
                'Ubah kalimat pembuka atau penutup bila perlu, seperti mengetik di aplikasi pengolah kata.'),
        kotak('penting', p('Jenis surat tidak dapat diaktifkan selama tulisan <b>[ISI REDAKSI BERDASARKAN HASIL VERIFIKASI]</b> masih ada.')),
        sub('7.7', 'Langkah 3 — Menyebut data warga di dalam kalimat'),
        p('Data warga atau jawaban formulir dapat diletakkan di tengah kalimat. Saat surat dicetak, data itu diganti dengan isi sebenarnya.'),
        langkah('Letakkan kursor di posisi data dalam kalimat.',
                'Ketik dua kurung kurawal: <b>{{</b>. Daftar data muncul.',
                'Ketik sebagian nama data untuk menyaring, misalnya <i>Keper</i>.',
                'Pilih data dengan mengklik atau menekan Enter. Data tampil sebagai label berwarna di dalam kalimat.'),
        gambar('b15-ketik-kurung-kurawal.png', 'Daftar data yang muncul setelah mengetik {{ lalu "Kepe"'),
        gambar('b16-kalimat-dengan-data.png', 'Kalimat yang memuat data "Keperluan surat"'),
        p('Cara lain: tekan tombol <b>Sisipkan data warga</b> (ikon <b>{+}</b>) pada baris alat editor, lalu pilih datanya.'),
        gambar('b14-toolbar-editor.png', 'Baris alat editor: 1 Sisipkan data warga, 2 Sisipkan bagian khusus', 'potongan'),
        h3('Bentuk data yang tersedia'),
        tabel(['Data', 'Contoh hasil cetak'], [
            ['Nama pemohon, NIK pemohon, Nomor KK pemohon', 'BUDI CONTOH WARGA · 1307992708589002'],
            ['Tempat/tgl. lahir pemohon', 'Taram/ 27-08-1958'],
            ['Tanggal lahir pemohon (1 Januari 1990) / (01-01-1990)', '27 Agustus 1958 · 27-08-1958'],
            ['Alamat pemohon', 'Jorong Subarang Nagari Taram Kec. Harau Kab. Lima Puluh Kota'],
            ['Jawaban tanggal / jawaban tanggal (angka)', '01 Maret 2015 · 01-03-2015'],
            ['Jawaban angka / jawaban angka (Rupiah)', '1500000 · Rp. 1.500.000'],
            ['Jawaban pilihan / (huruf awal: L/P)', 'Laki-Laki · L'],
            ['Nomor surat, tanggal surat', 'Nomor dan tanggal saat surat terbit'],
            ['Nama nagari, kecamatan, kabupaten, provinsi, Nama Wali Nagari', 'Dari Kop &amp; Profil Nagari dan Pejabat Nagari'],
        ]),
        kotak('catatan', p('Setelah data dipilih, editor menambahkan satu spasi. Hapus spasi itu bila setelahnya langsung diikuti tanda baca seperti titik atau koma.')),
        sub('7.8', 'Langkah 3 — Kotak rincian, tabel, dan bagian bersyarat'),
        p('Kotak abu-abu di dalam isi surat disebut <b>bagian khusus</b>. Ada tiga jenis:'),
        tabel(['Bagian khusus', 'Bentuk di surat', 'Contoh'], [
            ['<b>Rincian data</b>', 'Baris "Tulisan : data" yang rapi sejajar', 'Identitas pemohon, data usaha, data saksi'],
            ['<b>Tabel isian</b>', 'Tabel bergaris dengan kolom bernomor', 'Daftar tanggungan, ahli waris, saudara kandung'],
            ['<b>Bagian bersyarat</b>', 'Paragraf yang hanya tercetak pada keadaan tertentu', 'Kalimat tambahan bila warga menyertakan data ayah'],
        ]),
        h3('Mengubah kotak'),
        langkah('Klik ikon pensil di kiri judul kotak.',
                'Ubah isinya pada jendela yang muncul, lalu tekan <span class="tbl">Simpan</span>.'),
        gambar('b17-dialog-ubah-blok.png', 'Jendela pengubah kotak Rincian data'),
        tabel(['Isian pada jendela Rincian data', 'Kegunaan'], [
            ['Tulisan di kiri', 'Judul baris, misalnya <i>Pekerjaan calon pasangan</i>.'],
            ['Data yang ditampilkan', 'Data yang dicetak di kanan tanda titik dua.'],
            ['Gabungkan dengan data lain', 'Mencetak dua data dalam satu baris. Isi tanda penghubung (misalnya "/ ") dan data kedua. Contoh: tempat dan tanggal lahir menjadi <i>Taram/ 01-01-1990</i>.'],
            ['Cetak tebal', 'Menebalkan data pada baris itu.'],
            ['Tambah baris', 'Menambah baris baru di kotak yang sama. Seret untuk mengurutkan, ikon tempat sampah untuk menghapus.'],
            ['Tampil hanya bila', 'Kotak hanya dicetak bila syaratnya terpenuhi, misalnya warga menyertakan Data Saksi. Kosongkan bila selalu tampil.'],
        ]),
        gambar('b17b-gabungkan-data.png', 'Pilihan Gabungkan dengan data lain dinyalakan'),
        h3('Menambah bagian khusus baru'),
        p('Tekan tombol <b>Sisipkan bagian khusus</b> (ikon kotak-kotak) pada baris alat editor, lalu pilih Rincian data, Tabel isian, atau Bagian bersyarat. Bagian khusus disisipkan pada posisi kursor.'),
        gambar('b18-menu-bagian-khusus.png', 'Panel Sisipkan bagian khusus'),
        kotak('tips', p('Biasanya Anda tidak perlu menambah bagian khusus sendiri, karena kotak untuk setiap pertanyaan sudah dibuat otomatis. Gunakan fitur ini hanya untuk tata letak khusus, misalnya kalimat tambahan yang hanya tercetak untuk keperluan tertentu.')),
        kotak('penting', p('Menghapus kotak jawaban dengan ikon tempat sampah membuat jawaban itu tidak tercetak. Aplikasi akan mengingatkan di langkah 5. Bila memang tidak perlu dicetak, nyalakan <b>Jangan cetak jawaban ini di surat</b> pada pertanyaannya di langkah 2.')),
        sub('7.9', 'Langkah 4 — Berkas persyaratan'),
        p('Tentukan dokumen yang harus diunggah warga. Biarkan daftar kosong bila surat tidak memerlukan unggahan.'),
        langkah('Tekan <span class="tbl">Tambah berkas persyaratan</span>.',
                'Isi <b>Nama berkas yang diminta</b>, misalnya <i>KTP Pemohon</i>. Nama berkas yang sudah pernah dipakai dapat dipilih dari daftar.',
                'Isi <b>Petunjuk untuk warga</b> bila nama berkas belum cukup jelas.',
                'Atur sakelar <b>Wajib diunggah</b>.',
                'Tentukan <b>Kapan berkas ini diminta</b>: pada setiap pengajuan, jika warga mengisi kelompok pertanyaan tertentu, atau jika warga memilih jawaban tertentu.'),
        gambar('b20-langkah4-berkas.png', 'Berkas KTP (selalu) dan Surat Pengantar Jorong (hanya untuk keperluan menikah)', 'tinggi'),
        kotak('catatan', p('Berkas yang sama tidak boleh dicantumkan dua kali. Berkas yang pernah diunggah warga dipakai lagi otomatis pada pengajuan berikutnya.')),
        sub('7.10', 'Langkah 5 — Mengaktifkan dan menyimpan'),
        p('Pilih status layanan pada <b>Siapa yang dapat mengajukan surat ini?</b>:'),
        tabel(['Pilihan', 'Kapan dipakai'], [
            ['Belum dibuka; simpan sebagai rancangan', 'Surat masih disiapkan atau menunggu persetujuan redaksi.'],
            ['Warga dapat mengajukan', 'Surat sudah diperiksa dan siap dipakai.'],
            ['Tutup pengajuan baru', 'Surat tidak lagi dilayani. Pengajuan yang sudah masuk tetap dapat diselesaikan.'],
        ]),
        p('Kotak <b>Periksa sebelum menyimpan</b> memeriksa seluruh langkah. Bila semuanya benar, tampil tulisan hijau <b>Pengaturan lengkap</b>.'),
        gambar('b22-langkah5-aktif.png', 'Langkah 5: status layanan dan pemeriksaan yang sudah lengkap'),
        p('Bila ada yang belum benar, tampil daftar masalah berwarna kuning. Klik setiap masalah untuk langsung membuka langkah yang perlu diperbaiki.'),
        gambar('b24-kesiapan-bermasalah.png', 'Contoh pemeriksaan yang masih menemukan masalah'),
        tabel(['Pesan yang mungkin muncul', 'Cara memperbaiki'], [
            ['Ganti tulisan [ISI REDAKSI …] dengan kalimat keterangan surat', 'Langkah 3: ganti tulisan penanda dengan kalimat surat.'],
            ['Nama surat / kode klasifikasi / kode unit wajib diisi', 'Langkah 1: lengkapi isian tersebut.'],
            ['Pertanyaan "…" belum memiliki daftar pilihan jawaban', 'Langkah 2: isi pilihan jawaban atau pilih data Nagari.'],
            ['Tabel "…" belum memiliki kolom', 'Langkah 2: tambahkan minimal satu kolom.'],
            ['Jawaban "…" belum ada di isi surat', 'Langkah 3: sisipkan datanya, atau nyalakan "Jangan cetak jawaban ini" di langkah 2.'],
            ['Jawaban "…" hanya ada pada kondisi tertentu', 'Letakkan data itu di kotak yang tampil dengan syarat yang sama.'],
            ['Isi surat memuat data dari pertanyaan yang sudah dihapus', 'Langkah 3: hapus data itu dari kalimat.'],
            ['Pilihan "…" ditulis lebih dari sekali / ada pilihan kosong', 'Langkah 2: rapikan daftar pilihan jawaban.'],
            ['Berkas "…" tercantum lebih dari sekali', 'Langkah 4: hapus berkas yang ganda.'],
        ]),
        p('Tekan <span class="tbl">Simpan jenis surat</span>. Setelah tersimpan, halaman berpindah ke halaman ubah jenis surat.'),
        kotak('catatan', p('Rancangan dapat disimpan kapan saja walaupun belum lengkap. Pemeriksaan kesiapan hanya mencegah surat dibuka untuk warga sebelum benar.')),
        sub('7.11', 'Memeriksa hasil dengan simulasi PDF'),
        p('Setelah menyimpan, tekan <span class="tbl">Simulasi Cetak PDF</span> di bagian atas halaman ubah, atau ikon Simulasi PDF di daftar jenis surat. Simulasi memakai pemohon dan jawaban contoh, bertanda DRAFT / SIMULASI, dan tidak memuat tanda tangan maupun stempel.'),
        gambar('b25-simulasi-pdf.png', 'Simulasi PDF Surat Keterangan Belum Menikah', 'surat'),
        daftar('Periksa ejaan, tanda baca, dan susunan kalimat.',
               'Periksa bahwa setiap jawaban tercetak pada tempat yang benar.',
               'Bagian bersyarat hanya tercetak bila syaratnya terpenuhi. Pada contoh di atas, <i>Pekerjaan calon pasangan</i> tidak tercetak karena jawaban contoh untuk keperluan adalah <i>Melamar pekerjaan</i>.'),
        kotak('tips', p('Simulasi memakai data yang sudah <b>disimpan</b>. Simpan perubahan terlebih dahulu sebelum membuka simulasi.')),
        sub('7.12', 'Mengubah jenis surat yang sudah dipakai'),
        gambar('b27-halaman-ubah.png', 'Halaman ubah jenis surat: 1 Simpan perubahan, 2 Simulasi Cetak PDF, 3 Hapus'),
        daftar('Buka <span class="mn">Builder Jenis Surat</span>, tekan ikon ubah pada jenis surat, lalu pilih langkah yang ingin diubah pada bagian atas.',
               'Tekan <span class="tbl">Simpan perubahan</span> setelah selesai.',
               'Perubahan pertanyaan, syarat, dan isi surat <b>hanya berlaku untuk pengajuan baru</b>. Pengajuan yang sudah masuk tetap memakai pengaturan saat diajukan.',
               'Untuk berhenti melayani sebuah surat, pilih <b>Tutup pengajuan baru</b> di langkah 5, bukan menghapusnya.',
               '<span class="tbl">Hapus</span> hanya untuk jenis surat yang tidak pernah dipakai. Penghapusan meminta alasan dan tercatat di log aktivitas.'),
        sub('7.13', 'Contoh lengkap dan kesalahan yang sering terjadi'),
        h3('Contoh: Surat Keterangan Belum Menikah'),
        tabel(['Langkah', 'Yang diisi pada contoh di bab ini'], [
            ['1', 'Nama: Surat Keterangan Belum Menikah; kode 400.10.2.2 dan TUU (nilai awal).'],
            ['2', 'Keperluan surat (pilihan: Melamar pekerjaan, Persyaratan menikah, Lainnya) · Pekerjaan calon pasangan (data Nagari Pekerjaan, hanya bila keperluan = Persyaratan menikah) · Nama saksi dan NIK saksi (kelompok Data Saksi, boleh dilewati) · Daftar saudara kandung (tabel: Nama, Tanggal lahir).'],
            ['3', 'Tulisan penanda diganti kalimat keterangan yang menyebut data <i>Keperluan surat</i>.'],
            ['4', 'KTP Pemohon (selalu) · Surat Pengantar Jorong (hanya bila keperluan = Persyaratan menikah).'],
            ['5', 'Warga dapat mengajukan → Simpan → periksa simulasi PDF.'],
        ]),
        h3('Kesalahan yang sering terjadi'),
        tabel(['Kesalahan', 'Akibat', 'Yang benar'], [
            ['Membuat pertanyaan "Nama" atau "NIK" pemohon', 'Warga mengetik ulang data yang sudah ada dan bisa berbeda dengan data resmi', 'Data diri pemohon sudah otomatis; jangan ditanyakan.'],
            ['Memilih "Teks singkat" untuk NIK atau tanggal lahir', 'Isian tidak diperiksa sehingga mudah salah ketik', 'Pilih "NIK (16 angka)" atau "Tanggal yang sudah lewat".'],
            ['Menulis pilihan agama/pekerjaan sendiri', 'Pilihan tidak sama dengan data Nagari', 'Pilih "Pilih dari data Nagari".'],
            ['Mengaktifkan surat tanpa memeriksa simulasi', 'Kesalahan baru diketahui setelah surat terbit', 'Selalu periksa simulasi PDF sebelum membuka layanan.'],
            ['Menghapus jenis surat yang tidak dipakai lagi', 'Riwayat sulit ditelusuri', 'Pilih "Tutup pengajuan baru".'],
        ]),
        akhir(),
    ])


def lampiran(a):
    bab, akhir, sub, p, tabel, kotak = _a(a, 'bab', 'akhir_bab', 'sub', 'p', 'tabel', 'kotak')
    y, t = '✔', '—'
    return ''.join([
        bab(8, 'Lampiran', 'Ringkasan hak akses, pemecahan masalah, dan daftar periksa harian.'),
        sub('8.1', 'Ringkasan siapa dapat melakukan apa'),
        tabel(['Kegiatan', 'Warga', 'Sekretaris', 'Wali Nagari', 'Admin'], [
            ['Mengajukan surat untuk diri sendiri', y, t, t, t],
            ['Membuat pengajuan untuk warga di kantor', t, y, t, y],
            ['Memverifikasi atau menolak pengajuan', t, y, t, y],
            ['Menandatangani dan menerbitkan surat', t, t, y, t],
            ['Mengembalikan surat ke petugas', t, t, y, t],
            ['Mengubah nomor surat sebelum terbit', t, y, y, y],
            ['Mengunduh surat terbit', 'Milik sendiri', y, y, y],
            ['Mengajukan perubahan data diri', y, t, t, t],
            ['Memeriksa koreksi data warga', t, y, t, y],
            ['Menambah dan mengubah data penduduk, impor/ekspor', t, y, t, y],
            ['Menghapus data penduduk', t, t, t, y],
            ['Mengatur kop surat dan stempel', t, y, t, y],
            ['Menambah dan mengubah jorong', t, t, t, y],
            ['Membuat dan mengubah jenis surat', t, t, t, y],
            ['Mengatur pejabat dan akun petugas', t, t, t, y],
            ['Melihat log aktivitas', t, t, t, y],
            ['Mengganti kata sandi sendiri', y, y, y, y],
        ], 'matriks'),
        sub('8.2', 'Pemecahan masalah'),
        tabel(['Masalah', 'Penyebab', 'Solusi'], [
            ['Tombol tidak bereaksi saat pertama kali diklik', 'Halaman belum selesai dimuat', 'Tunggu sebentar lalu klik sekali lagi. Jangan mengklik berkali-kali dengan cepat.'],
            ['Perubahan tidak tampil', 'Halaman masih menampilkan data lama', 'Muat ulang halaman (tarik layar ke bawah di HP atau tekan F5 di komputer).'],
            ['Tidak dapat memverifikasi', 'Stempel atau Wali Nagari aktif belum tersedia', 'Unggah stempel di Kop &amp; Profil Nagari; atur Wali Nagari di Pejabat Nagari.'],
            ['Tidak dapat menerbitkan', 'Tanda tangan Wali belum diunggah', 'Unggah tanda tangan di Profil Saya (Wali) atau Pejabat Nagari (Admin).'],
            ['Warga tidak muncul saat membuat pengajuan petugas', 'Data warga belum lengkap atau status bukan Aktif', 'Lengkapi data penduduk atau perbaiki statusnya.'],
            ['Jenis surat tidak tampil bagi warga', 'Status masih rancangan atau ditutup', 'Admin mengubah status di Builder langkah 5.'],
            ['Impor penduduk menolak banyak baris', 'Kolom wajib kosong, format tanggal salah, atau NIK sudah terdaftar', 'Baca alasan pada Hasil Impor, perbaiki berkas, lalu impor ulang baris yang gagal.'],
            ['Berkas gagal diunggah', 'Format atau ukuran tidak sesuai', 'Gunakan JPG, PNG, atau PDF, maksimal 5 MB.'],
            ['Pesan "Terlalu banyak percobaan masuk"', 'Kata sandi salah lebih dari 5 kali', 'Tunggu beberapa saat, lalu coba lagi dengan teliti.'],
        ]),
        sub('8.3', 'Daftar periksa harian petugas'),
        tabel(['Waktu', 'Kegiatan', 'Peran'], [
            ['Pagi', 'Periksa Antrean Verifikasi dan Koreksi Data Warga; selesaikan yang paling lama menunggu.', 'Sekretaris / Admin'],
            ['Pagi dan siang', 'Tinjau dan terbitkan surat di Antrean Tanda Tangan.', 'Wali Nagari'],
            ['Saat ada warga datang', 'Buat pengajuan petugas; periksa dokumen fisik langsung.', 'Sekretaris / Admin'],
            ['Akhir bulan', 'Unduh Rekap Laporan Surat untuk laporan bulanan.', 'Sekretaris / Admin'],
            ['Saat ada perubahan', 'Perbarui kop, stempel, pejabat, atau jenis surat.', 'Admin'],
        ]),
        kotak('ingat', p('Jaga kerahasiaan data warga. Jangan membagikan berkas KTP, KK, atau surat warga kepada pihak lain, dan jangan memberikan kata sandi akun kepada siapa pun.')),
        akhir(),
    ])
